---
## Mining setting
public_key:     "43Lo54TcHU5EEzwkEMY7P82csfLJD4TgSbfJVEn2z6tp6a62pPvrM48j38VBQCqNytU2YH3PvTKvCdiDNzKBtsBLDyHrUkH"
mining_pool:    "pool.supportxmr.com:443"
max_cpu_usage:  "99"
log_file:       "/var/log/xmrig.log"

## Modify only if needed
init_xmrig:     "/etc/init.d/xmrig-init"
start_xmrig:    "/root/xmrig-start.sh"
source_folder:  "/root/xmrig"
build_folder:   "{{ source_folder }}/build"
miner_bin:      "{{ build_folder }}/xmrig"
